import { SignIn } from "@clerk/nextjs";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Imaginara | Sign-in",
  description: "Generated by  next app",
};

export default function Page() {
  return <SignIn />;
}