"use client"

import Image from "next/image";
import { Metadata } from "next";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import Topbar from "@/components/shared/Topbar"; 

// export const metadata: Metadata = {
//   title: "Imaginara | Photographers socials & Portfolio",
//   description: "Generated by  next app",
// };


export default function Home() {
  return (
      <>
        <SignedIn>
          <div className="px-[20%] py-[15px]">
            {/* <h1 className="text-white">
              hello
            </h1> */}

            <div></div>
          </div>
        </SignedIn> 
      </>
  );
}
