import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Imaginara",
  description: "Generated by  next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
<ClerkProvider>
    <html lang="en" className="flex justify-center items-center p-[7rem]">
      <body className={`${inter.className} bg-black login-page`}>
          {children}
      </body>
    </html>
</ClerkProvider>

  );
}




