import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Imaginara | Explore page",
    description: "Generated by  next app",
  };


function Explore() {
    return(
        <>
            <h2 className="text-white">
                Explore
            </h2>
        </>
    )
}

export default Explore;