import { SignUp } from "@clerk/nextjs";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Imaginara | Sign-up",
  description: "Generated by  next app",
};


export default function Page() {
  return <SignUp />;
}